-- Crear base de datos
CREATE DATABASE IF NOT EXISTS BD_MR;
USE BD_MR;

-- Crear tabla de clientes
CREATE TABLE TB_CLIENTS (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  SECOND_NAME VARCHAR(50) NOT NULL,
  PHONE VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
);

-- Crear tabla de mesas
CREATE TABLE TB_TABLES (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
);

-- Crear tabla de reservas
CREATE TABLE TB_RESERVATIONS (
  ID INT NOT NULL AUTO_INCREMENT,
  DATE DATETIME NOT NULL,
  NUM_CLIENTS INT NOT NULL,
  CLIENT_ID INT NOT NULL,
  TABLE_ID INT NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (CLIENT_ID) REFERENCES TB_CLIENTS(ID),
  FOREIGN KEY (TABLE_ID) REFERENCES TB_TABLES(ID)
);

-- Crear tabla de trabajadores
CREATE TABLE TB_WORKERS (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  SECOND_NAME VARCHAR(50) NOT NULL,
  PHONE VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  CHARGE VARCHAR(1) NOT NULL,
  PRIMARY KEY (ID)
);
